### PR TITLE
CI: Only compile for x41 chips using IDE versions that avoid exceeding Windows maximum path length

### PR DESCRIPTION
**Pull request by per1234**
In Arduino IDE 1.8.5 and older versions, boards with a lot of custom menus can cause the path of the cached core to exceed Windows' `MAX_PATH`, resulting in a compilation error. To avoid this issue, an `#error` directive was added that causes compilation to fail when using Arduino IDE < 1.8.6 and ATtiny841 or ATtiny441, thus the Travis CI build must be updated to avoid compiling for these boards with earlier IDE versions.

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Thanks!

**Comment by SpenceKonde** [comment]
The build after merging errored with a bizzare new error on every test:

The command "codespell --skip=*.lst,"${TRAVIS_BUILD_DIR}/.git","${TRAVIS_BUILD_DIR}/avr/travis-ci" --ignore-words="${TRAVIS_BUILD_DIR}/avr/travis-ci/etc/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"" failed and exited with 4 during .

**Comment by per1234** [comment]
codespell is used to check for commonly misspelled words. The build failed because commonly misspelled words were found:
```
/home/travis/build/SpenceKonde/ATTinyCore/avr/libraries/Wire/src/SoftI2CMaster.h:128: interruptable  ==> interruptible
/home/travis/build/SpenceKonde/ATTinyCore/avr/libraries/SPI/SPI.h:131: compiletime  ==> compile time
/home/travis/build/SpenceKonde/ATTinyCore/avr/libraries/SPI/SPI.cpp:560: objec  ==> object
/home/travis/build/SpenceKonde/ATTinyCore/avr/extras/ATtiny_x41.md:17: whilest  ==> whilst
```
The reason why the build passed previously with these same words in place and now fails is that codespell's list of commonly misspelled words is continuously being improved and added to and a new version of codespell was released between the time of the passing and the failing build. I'll submit a PR fixing the misspelled words.

**Comment by SpenceKonde** [comment]
Don't worry about it, I fixed the misspelled words.
