### ISSUE TITLE
Wire.h compilation error with ATTiny85

### ISSUE THREAD

**Issue by datacute** [SpenceKonde/ATTinyCore#244]
After upgrading Arduino IDE to 1.8.7 I had a compilation error:
Wire.h:123:5: error: 'size_t' does not name a type
Adding an include of either <stdio.h> or "Stream.h" at line 93 fixed the problem.

**Comment by SpenceKonde** [comment]
Closed per #249.
