### ISSUE TITLE
Error compiling for board with empty sketch

### ISSUE THREAD

**Issue by Combinacijus** [SpenceKonde/ATTinyCore#771]
### Info
`Arduino IDE 1.8.13`
`Windows 10` and `Ubuntu 22.04`
`megaTinyCore version 2.67 (latest)`
Board: `ATtiny3217/1617/1607/817/807/417 w/Optiboot` but I'm pretty sure it happens with others too

### Problem
Even default code with empty setup() and loop() won't compile

### Workaround / Fix
Fixed by downgrading to 2.6.5 or 2.6.4 (haven't tested earlier versions)

### Notes
It works with earlier versions (<2.6.7) so it's good for me. Just wanted to document it

### Setup
1. Additional Boards Manager URLs: http://drazzy.com/package_drazzy.com_index.json
2. Download megaTinyCore version 2.67 (latest)
3. Select board (or probably any other): ATtiny3217/1617/1607/817/807/417 w/Optiboot
4. Create new sketch and verify/compile (alt + r)

Code (default empty):
```
void setup() {}
void loop() {}
```

Error:
```
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c: In function 'analogWrite':
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1205:13: error: 'set_inven' undeclared (first use in this function); did you mean 'strnlen'?
             set_inven = 1;
             ^~~~~~~~~
             strnlen
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1205:13: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1307:5: error: break statement not within loop or switch
     break;
     ^~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1317:5: error: case label not within a switch statement
     case NOT_ON_TIMER: /*falls through*/
     ^~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1318:5: error: 'default' label not within a switch statement
     default:
     ^~~~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1325:7: error: break statement not within loop or switch
       break;
       ^~~~~
In file included from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\api/ArduinoAPI.h:52:0,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\Arduino.h:26,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_private.h:32,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:25:
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c: At top level:
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\api/Common.h:16:26: error: expected ')' before numeric constant
 #define OUTPUT           1    /* used for pinMode() */
                          ^
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1330:16: note: in expansion of macro 'OUTPUT'
   pinMode(pin, OUTPUT);
                ^~~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1331:1: error: expected identifier or '(' before '}' token
 } // end of analogWrite
 ^
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c: In function 'analogWrite':
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1205:13: error: 'set_inven' undeclared (first use in this function); did you mean 'strnlen'?
             set_inven = 1;
             ^~~~~~~~~
             strnlen
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1205:13: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1307:5: error: break statement not within loop or switch
     break;
     ^~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1317:5: error: case label not within a switch statement
     case NOT_ON_TIMER: /*falls through*/
     ^~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1318:5: error: 'default' label not within a switch statement
     default:
     ^~~~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1325:7: error: break statement not within loop or switch
       break;
       ^~~~~
In file included from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\api/ArduinoAPI.h:52:0,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\Arduino.h:26,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_private.h:32,
                 from C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:25:
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c: At top level:
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\api/Common.h:16:26: error: expected ')' before numeric constant
 #define OUTPUT           1    /* used for pinMode() */
                          ^
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1330:16: note: in expansion of macro 'OUTPUT'
   pinMode(pin, OUTPUT);
                ^~~~~~
C:\Users\username\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.6.7\cores\megatinycore\wiring_analog.c:1331:1: error: expected identifier or '(' before '}' token
 } // end of analogWrite
 ^
exit status 1
Error compiling for board ATtiny3217/1617/1607/817/807/417 w/Optiboot.
exit status 1
Error compiling for board ATtiny3217/1617/1607/817/807/417 w/Optiboot.
```

**Comment by SpenceKonde** [comment]
1. You posted this is the ATTinyCore section, this issue is with megaTinyCore. 
2. You are the tenth person to report this and it is fixed in github I'm just trying to get all CI to pass before I release 2.6.8

**Comment by Combinacijus** [comment]
@SpenceKonde 
That explains why I couldn't find the issue in this repo, my bad and thanks for the work
